const router=require('express').Router();const pool=require('../db');
const types={receipts:'RECEIPT',deliveries:'DELIVERY',transfers:'TRANSFER'};
router.get('/ledger',async(_req,res,next)=>{try{const {rows}=await pool.query('SELECT l.*,p.name product_name,w.name warehouse_name,o.ref FROM stock_ledger l JOIN products p ON p.id=l.product_id JOIN warehouses w ON w.id=l.warehouse_id LEFT JOIN operations o ON o.id=l.operation_id ORDER BY l.created_at DESC LIMIT 200');res.json({success:true,ledger:rows});}catch(e){next(e);}});
for(const [path,type] of Object.entries(types)){
 router.get('/'+path,async(_req,res,next)=>{try{const {rows}=await pool.query('SELECT o.*,p.name product_name,sw.name source_name,dw.name destination_name FROM operations o LEFT JOIN products p ON p.id=o.product_id LEFT JOIN warehouses sw ON sw.id=o.source_warehouse_id LEFT JOIN warehouses dw ON dw.id=o.destination_warehouse_id WHERE o.type=$1 ORDER BY o.created_at DESC',[type]);res.json({success:true,records:rows.map(r=>({ref:r.ref,type:r.type.toLowerCase(),product:r.product_name,from:r.source_name||r.from_label,to:r.destination_name||r.to_label,contact:r.contact||'',qty:Number(r.quantity),date:r.scheduled_date,status:r.status}))});}catch(e){next(e);}});
 router.post('/'+path,async(req,res,next)=>{try{const b=req.body;const qty=Number(b.qty??b.quantity??1);if(!b.from||!b.to||!Number.isFinite(qty)||qty<=0)return res.status(400).json({success:false,message:'From, to, and a positive quantity are required'});let productId=null,src=null,dst=null;
 if(type==='TRANSFER'||b.productId||b.product){const pr=await pool.query('SELECT id FROM products WHERE id::text=$1 OR lower(name)=lower($1) OR sku=$1 LIMIT 1',[String(b.productId||b.product||'')]);if(!pr.rowCount)return res.status(400).json({success:false,message:'Product not found'});productId=pr.rows[0].id;}
 const wr=async(label)=>{const raw=String(label);const normalized=raw.toLowerCase()==='wh/stock1'?'Main Warehouse':raw.toLowerCase()==='wh/stock2'?'Warehouse 1':raw;const x=await pool.query('SELECT id FROM warehouses WHERE id::text=$1 OR lower(name)=lower($1) OR lower(code)=lower($1) LIMIT 1',[normalized]);if(x.rowCount)return x.rows[0].id;const y=await pool.query('INSERT INTO warehouses(name,code) VALUES($1,$2) RETURNING id',[normalized,normalized.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,10)||'WH']);return y.rows[0].id;};
 if(type==='RECEIPT')dst=await wr(b.to);else if(type==='DELIVERY')src=await wr(b.from);else{src=await wr(b.from);dst=await wr(b.to);}
 const prefix=type==='RECEIPT'?'IN':type==='DELIVERY'?'OUT':'INT';const ref=b.ref||`WH/${prefix}/${Date.now().toString().slice(-8)}`;const {rows}=await pool.query(`INSERT INTO operations(ref,type,status,product_id,source_warehouse_id,destination_warehouse_id,from_label,to_label,contact,quantity,scheduled_date) VALUES($1,$2,'draft',$3,$4,$5,$6,$7,$8,$9,COALESCE($10::date,CURRENT_DATE)) RETURNING *`,[ref,type,productId,src,dst,b.from,b.to,b.contact||null,qty,b.date||null]);const o=rows[0];res.status(201).json({success:true,record:{ref:o.ref,status:o.status,from:o.from_label,to:o.to_label,product:b.product||null,qty:Number(o.quantity),date:o.scheduled_date}});
 }catch(e){if(e.code==='23505')return res.status(409).json({success:false,message:'Reference already exists'});next(e);}});
 router.patch('/'+path+'/:ref',async(req,res,next)=>{const client=await pool.connect();try{const status=String(req.body.status||'').toLowerCase();if(!['draft','waiting','ready','done','canceled'].includes(status))return res.status(400).json({success:false,message:'Invalid status'});await client.query('BEGIN');const q=await client.query('SELECT * FROM operations WHERE ref=$1 AND type=$2 FOR UPDATE',[req.params.ref,type]);if(!q.rowCount){await client.query('ROLLBACK');return res.status(404).json({success:false,message:'Operation not found'});}const o=q.rows[0];
 if(status==='done'&&o.status!=='done'){
  if(!o.product_id){await client.query('ROLLBACK');return res.status(400).json({success:false,message:'Select a product and quantity before validating this operation'});}
  const move=async(wh,delta)=>{const cur=await client.query('SELECT quantity FROM stock WHERE product_id=$1 AND warehouse_id=$2 FOR UPDATE',[o.product_id,wh]);const n=Number(cur.rows[0]?.quantity||0)+delta;if(n<0)throw new Error('Insufficient stock');if(cur.rowCount)await client.query('UPDATE stock SET quantity=$1 WHERE product_id=$2 AND warehouse_id=$3',[n,o.product_id,wh]);else await client.query('INSERT INTO stock(product_id,warehouse_id,quantity) VALUES($1,$2,$3)',[o.product_id,wh,n]);return delta;};
  if(type==='RECEIPT'){await move(o.destination_warehouse_id,Number(o.quantity));await client.query("INSERT INTO stock_ledger(operation_id,product_id,warehouse_id,change_quantity,note) VALUES($1,$2,$3,$4,'Validated receipt')",[o.id,o.product_id,o.destination_warehouse_id,o.quantity]);}
  if(type==='DELIVERY'){await move(o.source_warehouse_id,-Number(o.quantity));await client.query("INSERT INTO stock_ledger(operation_id,product_id,warehouse_id,change_quantity,note) VALUES($1,$2,$3,$4,'Validated delivery')",[o.id,o.product_id,o.source_warehouse_id,-Number(o.quantity)]);}
  if(type==='TRANSFER'){await move(o.source_warehouse_id,-Number(o.quantity));await move(o.destination_warehouse_id,Number(o.quantity));await client.query("INSERT INTO stock_ledger(operation_id,product_id,warehouse_id,change_quantity,note) VALUES($1,$2,$3,$4,'Transfer out'),($1,$2,$5,$6,'Transfer in')",[o.id,o.product_id,o.source_warehouse_id,-Number(o.quantity),o.destination_warehouse_id,o.quantity]);}
 }
 const updated=await client.query('UPDATE operations SET status=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[status,o.id]);await client.query('COMMIT');res.json({success:true,record:{ref:updated.rows[0].ref,status:updated.rows[0].status}});
 }catch(e){await client.query('ROLLBACK');if(e.message==='Insufficient stock')return res.status(409).json({success:false,message:e.message});next(e);}finally{client.release();}});
}
module.exports=router;
router.post('/adjustments',async(req,res,next)=>{const c=await pool.connect();try{const {product,productId,warehouse,location,countedQuantity,quantity}=req.body;const counted=Number(countedQuantity??quantity);if((!product&&!productId)||(!warehouse&&!location)||!Number.isFinite(counted)||counted<0)return res.status(400).json({success:false,message:'Product, location, and a non-negative counted quantity are required'});await c.query('BEGIN');const p=await c.query('SELECT id FROM products WHERE id::text=$1 OR sku=$1 OR lower(name)=lower($1) LIMIT 1',[String(productId||product)]);if(!p.rowCount)throw Object.assign(new Error('Product not found'),{status:404});const w=await c.query('SELECT id FROM warehouses WHERE id::text=$1 OR code=$1 OR lower(name)=lower($1) LIMIT 1',[String(warehouse||location)]);if(!w.rowCount)throw Object.assign(new Error('Warehouse not found'),{status:404});const old=await c.query('SELECT quantity FROM stock WHERE product_id=$1 AND warehouse_id=$2 FOR UPDATE',[p.rows[0].id,w.rows[0].id]);const delta=counted-Number(old.rows[0]?.quantity||0);if(old.rowCount)await c.query('UPDATE stock SET quantity=$1 WHERE product_id=$2 AND warehouse_id=$3',[counted,p.rows[0].id,w.rows[0].id]);else await c.query('INSERT INTO stock(product_id,warehouse_id,quantity) VALUES($1,$2,$3)',[p.rows[0].id,w.rows[0].id,counted]);const ref=`WH/ADJ/${Date.now().toString().slice(-8)}`;const op=await c.query("INSERT INTO operations(ref,type,status,product_id,source_warehouse_id,from_label,to_label,quantity) VALUES($1,'ADJUSTMENT','done',$2,$3,$4,$4,GREATEST(ABS($5),0.01)) RETURNING id",[ref,p.rows[0].id,w.rows[0].id,warehouse||location,delta]);await c.query('INSERT INTO stock_ledger(operation_id,product_id,warehouse_id,change_quantity,note) VALUES($1,$2,$3,$4,$5)',[op.rows[0].id,p.rows[0].id,w.rows[0].id,delta,'Inventory count adjustment']);await c.query('COMMIT');res.status(201).json({success:true,ref,previousQuantity:Number(old.rows[0]?.quantity||0),countedQuantity:counted,change:delta});}catch(e){await c.query('ROLLBACK');res.status(e.status||500).json({success:false,message:e.message||'Adjustment failed'});}finally{c.release();}});


