const express = require('express');
const cors = require('cors');
require('dotenv').config();
const app = express();
app.use(cors());
app.use(express.json());
app.get('/api/health', (_req, res) => res.json({ success: true, message: 'StockSense API ready' }));
app.use('/api/auth', require('./routes/auth'));
app.use('/api/dashboard', require('./routes/dashboard'));
app.use('/api', require('./routes/operations'));
app.use((err, _req, res, _next) => { console.error(err); res.status(500).json({ success: false, message: 'Server error' }); });
const port = process.env.PORT || 5000;
app.listen(port, () => console.log(`StockSense API listening on ${port}`));
